# Generated by Django 5.0.2 on 2024-02-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra')], max_length=50)),
                ('city', models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur')], max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('courses', models.CharField(max_length=255)),
                ('photo', models.ImageField(default='media/Faculty_Photo/person.jpg', max_length=255, null=True, upload_to='media/Faculty_Photo')),
            ],
        ),
    ]
